---
- name: Converge
  hosts: all

  roles:
    - role: ../../../lfkdev.camino_messenger_bot

  post_tasks:
    - name: Check if Camino Messenger Bot systemd service files exist
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ bot.name }}.service"
        loop: "{{ camino_bots }}"
        loop_control:
          loop_var: bot

    - name: Check if Camino Messenger Bot config files exist
      ansible.builtin.stat:
        path: "{{ camino_config_path }}/{{ bot.name }}.yaml"
        loop: "{{ camino_bots }}"
        loop_control:
          loop_var: bot
